---
# Test playbook for Ansible role cdelgehier.openio-repository

- hosts: all
  gather_facts: true
  become: true

  roles:
    - role: role_under_test
      openio_repository_no_log: false
      openio_repository_mirror_host: mirror2.openio.io

    - role: role_under_test
      openio_repository_no_log: false
      openio_repository_mirror_host: mirror2.openio.io
      openio_repository_products:
        test:
          release: '20.04'
          password: 'bar'
          user: 'foo'

...
